### ISSUE TITLE
Better support for typed literal attributes

### ISSUE THREAD

**Issue by davesproson** [FAAM-146/vocal#6]
Say we have a definition which looks something like

```
variables:
  - meta:
        name: myvariable
        type: <int8>
    dimensions: ['time']
    attributes:
        frequency: 1
```

The frequency will be read in by the json/yaml parser as a python int (i.e. 64 bit),
resulting in a netCDF variable
```
byte myvariable(time)  ;
    myvariable:frequency = 1LL  ;
```
which may not be what we want, and may lead to typing errors when we check compliance.

This could potentially be solved by a literal placeholder which gives typing information,
something like
`frequency: <Literal[int8]: 1>`
